export const components = {
  LOGO: "LOGO",
  TITLE: "TITLE",
  BILL_TO: "BILL_TO",
  SYNQUE: "SYNQUE",
  TOTAL_AMOUNT: "TOTAL_AMOUNT",
  INVOICE_NUMBER: "INVOICE_NUMBER",
  ISSUED_DATE: "ISSUED_DATE",
  DUE_DATE: "DUE_DATE",
  ITEMS: "ITEMS",
  STAMP: "STAMP",
  PAYMENT_INSTRUCTIONS: "PAYMENT_INSTRUCTIONS",
  NOTES: "NOTES",
  AMOUNT_DUE: "AMOUNT_DUE",
};

export const ISSUED_TO = {
  CUSTOMER: "CUSTOMER",
};
